# Generated by Django 3.2.13 on 2022-05-27 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150)),
                ('relationship', models.CharField(max_length=8)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
                ('recipient_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt_file', models.FileField(upload_to='uploads/', verbose_name='첨부 파일')),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('contact', models.IntegerField()),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(max_length=45)),
                ('birth', models.DateField()),
                ('status', models.CharField(max_length=8)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recipient',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmotionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figure', models.CharField(max_length=256)),
                ('date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='emotion.recipient')),
            ],
            options={
                'db_table': 'emotion_result',
                'managed': True,
            },
        ),
    ]
